### ISSUE TITLE
Operator torch._ops.aten.unfold.default is not Aten Canonical

### ISSUE THREAD

**Issue by ari-ruokamo** [pytorch/executorch#5381]
### 🐛 Describe the bug

I'm experimenting in exporting various MSS models to Executorch. Following the example export scenario in Executorch Documentation the export terminates in 'Operator torch._ops.aten.unfold.default is not Aten Canonical' error.

Sample reference code input:

```
# Instatiate model & load weights
model = MyMSSModel(**config.model)
model = load(model, checkpoint_path)
model.eval()

# Dummy one second tensor
model_args = (torch.rand(1, 2, 44100),)

# 1. torch.export: Defines the program with the ATen operator set.
aten_dialect = export(model, model_args)

# 2. to_edge: Make optimizations for Edge devices
edge_program = to_edge(aten_dialect) ### <-- FAIL

# 3. to_executorch: Convert the graph to an ExecuTorch program
executorch_program = edge_program.to_executorch()

```
Export output:

```
Traceback (most recent call last):
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/arijr/projects/SCNet/scnet/export-executorch.py", line 29, in <module>
    edge_program = to_edge(aten_dialect)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1019, in to_edge
    edge_programs[name] = _generate_edge_program(name, config, program)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 680, in _generate_edge_program
    EXIRATenDialectVerifier(ops_set_to_not_decompose)(program.graph_module)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/verification/verifier.py", line 74, in __call__
    return self._check_graph_module(*args, **kwargs)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/_export/verifier.py", line 222, in _check_graph_module
    _check_valid_op(node.target)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/_export/verifier.py", line 205, in _check_valid_op
    self.check_valid_op(op)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/verification/verifier.py", line 116, in check_valid_op
    raise SpecViolationError(
**torch._export.verifier.SpecViolationError: Operator torch._ops.aten.unfold.default is not Aten Canonical.**

```

### Versions

Collecting environment information...
PyTorch version: 2.4.0+cpu
Is debug build: False
CUDA used to build PyTorch: Could not collect
ROCM used to build PyTorch: N/A

OS: Ubuntu 24.04 LTS (x86_64)
GCC version: (Ubuntu 13.2.0-23ubuntu4) 13.2.0
Clang version: Could not collect
CMake version: version 3.30.3
Libc version: glibc-2.39

Python version: 3.10.0 (default, Mar  3 2022, 09:58:08) [GCC 7.5.0] (64-bit runtime)
Python platform: Linux-6.8.0-40-generic-x86_64-with-glibc2.39
Is CUDA available: False
CUDA runtime version: 12.2.91
CUDA_MODULE_LOADING set to: N/A
GPU models and configuration: 
GPU 0: NVIDIA GeForce RTX 3090
GPU 1: NVIDIA GeForce RTX 3090
GPU 2: NVIDIA GeForce RTX 3090

Nvidia driver version: 535.183.01
cuDNN version: Probably one of the following:
/usr/lib/x86_64-linux-gnu/libcudnn.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_adv_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_cnn_train.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_infer.so.8.3.3
/usr/lib/x86_64-linux-gnu/libcudnn_ops_train.so.8.3.3
HIP runtime version: N/A
MIOpen runtime version: N/A
Is XNNPACK available: True

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        48 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               32
On-line CPU(s) list:                  0-31
Vendor ID:                            AuthenticAMD
Model name:                           AMD Ryzen 9 5950X 16-Core Processor
CPU family:                           25
Model:                                33
Thread(s) per core:                   2
Core(s) per socket:                   16
Socket(s):                            1
Stepping:                             2
Frequency boost:                      enabled
CPU(s) scaling MHz:                   58%
CPU max MHz:                          5083,3979
CPU min MHz:                          2200,0000
BogoMIPS:                             6799,81
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp lm constant_tsc rep_good nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba ibrs ibpb stibp vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a rdseed adx smap clflushopt clwb sha_ni xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local user_shstk clzero irperf xsaveerptr rdpru wbnoinvd arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif v_spec_ctrl umip pku ospke vaes vpclmulqdq rdpid overflow_recov succor smca fsrm debug_swap
L1d cache:                            512 KiB (16 instances)
L1i cache:                            512 KiB (16 instances)
L2 cache:                             8 MiB (16 instances)
L3 cache:                             64 MiB (2 instances)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-31
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Mitigation; Safe RET
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Retpolines; IBPB conditional; IBRS_FW; STIBP always-on; RSB filling; PBRSB-eIBRS Not affected; BHI Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] executorch==0.3.0a0+7d77d78
[pip3] numpy==2.1.1
[pip3] torch==2.4.0+cpu
[pip3] torchaudio==2.4.0+cpu
[pip3] torchsr==1.0.4
[pip3] torchvision==0.19.0
[conda] executorch                0.3.0a0+7d77d78          pypi_0    pypi
[conda] numpy                     2.1.1                    pypi_0    pypi
[conda] torch                     2.4.0+cpu                pypi_0    pypi
[conda] torchaudio                2.4.0+cpu                pypi_0    pypi
[conda] torchsr                   1.0.4                    pypi_0    pypi
[conda] torchvision               0.19.0                   pypi_0    pypi
(

**Comment by guangy10** [comment]
cc: @SS-JIA for core aten opset

**Comment by ari-ruokamo** [comment]
Knowing this might not be the solution but I tried disabling the dialect op check using,

`edge_program = to_edge(aten_dialect, compile_config=EdgeCompileConfig(_check_ir_validity=False))
`
the to_edge() phase completes, but the next phase terminates in an error:

```
Traceback (most recent call last):
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/arijr/projects/SCNet/scnet/export-executorch.py", line 33, in <module>
    executorch_program = edge_program.to_executorch()
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/program/_program.py", line 1196, in to_executorch
    new_gm_res = p(new_gm)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/fx/passes/infra/pass_base.py", line 41, in __call__
    res = self.call(graph_module)
  File "/home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/executorch/exir/passes/__init__.py", line 423, in call
    raise RuntimeError(f"Missing out variants: {missing_out_vars}")
RuntimeError: Missing out variants: {'aten::_unsafe_index_put'}
```

Any tips & assistance how to mitigate these issues is highly appreciated - thanks!

**Comment by ari-ruokamo** [comment]
By commenting line-by-line the source code of the model's forward()-function, I can see the following line (at least) triggers the issue's aten canonical error:

`        x = torch.stft(x, **self.stft_config, return_complex=True)
`

This is essential and I do not know how to workaround this one.

**Comment by divideconcept** [comment]
Does this mean it's impossible to export any model that uses stft/istft ? Is that planned ?

**Comment by ari-ruokamo** [comment]
Here's the graph output of the dummy forward-function. Where does the export compiler find a torch._ops.aten.unfold.default in there?

```
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, x: "f32[1, 2, 895088]"):
            # File: /home/arijr/miniconda3/envs/executorch/lib/python3.10/site-packages/torch/nn/functional.py:4552 in pad, code: return torch._C._nn.pad(input, pad, mode, value)
            pad: "f32[1, 2, 896000]" = torch.ops.aten.pad.default(x, [0, 912]);  x = None
            
            # File: /home/arijr/projects/SCNet/scnet/SCNet.py:331 in forward, code: x = x.reshape(-1, L)
            view: "f32[2, 896000]" = torch.ops.aten.view.default(pad, [-1, 896000]);  pad = None
            
            # File: /home/arijr/projects/SCNet/scnet/SCNet.py:333 in forward, code: x = torch.stft(x, **self.stft_config, return_complex=True)
            view_1: "f32[1, 2, 896000]" = torch.ops.aten.view.default(view, [1, 2, 896000]);  view = None
            pad_1: "f32[1, 2, 900096]" = torch.ops.aten.pad.default(view_1, [2048, 2048], 'reflect');  view_1 = None
            view_2: "f32[2, 900096]" = torch.ops.aten.view.default(pad_1, [2, 900096]);  pad_1 = None
            stft: "c64[2, 2049, 876]" = torch.ops.aten.stft.default(view_2, 4096, 1024, 4096, None, True, None, True);  view_2 = None
            
            # File: /home/arijr/projects/SCNet/scnet/SCNet.py:338 in forward, code: x = torch.istft(x, **self.stft_config)
            istft: "f32[2, 896000]" = torch.ops.aten.istft.default(stft, 4096, 1024, 4096, None, True, True);  stft = None
            return (istft,)

```
