### ISSUE TITLE
I want to understand the size of the memory allocated for the forward method on STM32's

### ISSUE THREAD

**Issue by ChristophKarlHeck** [pytorch/executorch#9447]
Hi guys,
This is the ExecuTorch Dialect of the CNN I run on the STM32Wb55

```
ExecuTorch Dialect
ExportedProgram:
    class GraphModule(torch.nn.Module):
        def forward(self, p_conv1d_1_weight: "f32[32, 1, 5]", p_conv1d_1_bias: "f32[32]", p_linear_weight: "f32[48, 64]", p_output_weight: "f32[2, 48]", x: "f32[1, 1, 100]"):
            # No stacktrace found for following nodes
            alloc: "f32[1, 32, 96]" = executorch_exir_memory_alloc(((1, 32, 96), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:174 in forward, code: x = self.conv1d_1(x)
            aten_convolution_default: "f32[1, 32, 96]" = torch.ops.aten.convolution.out(x, p_conv1d_1_weight, p_conv1d_1_bias, [1], [0], [1], False, [0], 1, out = alloc);  x = p_conv1d_1_weight = p_conv1d_1_bias = alloc = None
            
            # No stacktrace found for following nodes
            alloc_1: "f32[1, 32, 96]" = executorch_exir_memory_alloc(((1, 32, 96), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:175 in forward, code: x = F.relu(x)
            aten_relu_default: "f32[1, 32, 96]" = torch.ops.aten.relu.out(aten_convolution_default, out = alloc_1);  aten_convolution_default = alloc_1 = None
            
            # No stacktrace found for following nodes
            alloc_2: "f32[1, 32, 1, 96]" = executorch_exir_memory_alloc(((1, 32, 1, 96), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:177 in forward, code: x = self.pool(x) # compress to one convolution block
            aten_unsqueeze_copy_default: "f32[1, 32, 1, 96]" = torch.ops.aten.unsqueeze_copy.out(aten_relu_default, -2, out = alloc_2);  aten_relu_default = alloc_2 = None
            
            # No stacktrace found for following nodes
            alloc_3: "f32[1, 32, 1, 32]" = executorch_exir_memory_alloc(((1, 32, 1, 32), torch.float32))
            alloc_4: "i64[1, 32, 1, 32]" = executorch_exir_memory_alloc(((1, 32, 1, 32), torch.int64))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:177 in forward, code: x = self.pool(x) # compress to one convolution block
            aten_max_pool2d_with_indices_default = torch.ops.aten.max_pool2d_with_indices.out(aten_unsqueeze_copy_default, [1, 3], [1, 3], out = alloc_3, indices = alloc_4);  aten_unsqueeze_copy_default = alloc_3 = alloc_4 = None
            getitem: "f32[1, 32, 1, 32]" = aten_max_pool2d_with_indices_default[0];  aten_max_pool2d_with_indices_default = None
            
            # No stacktrace found for following nodes
            alloc_5: "f32[1, 32, 32]" = executorch_exir_memory_alloc(((1, 32, 32), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:177 in forward, code: x = self.pool(x) # compress to one convolution block
            aten_squeeze_copy_dims: "f32[1, 32, 32]" = torch.ops.aten.squeeze_copy.dims_out(getitem, [-2], out = alloc_5);  getitem = alloc_5 = None
            
            # No stacktrace found for following nodes
            alloc_6: "f32[1, 32, 32]" = executorch_exir_memory_alloc(((1, 32, 32), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:179 in forward, code: x = torch.transpose(x, 1, 2)
            aten_permute_copy_default: "f32[1, 32, 32]" = torch.ops.aten.permute_copy.out(aten_squeeze_copy_dims, [0, 2, 1], out = alloc_6);  aten_squeeze_copy_dims = alloc_6 = None
            
            # No stacktrace found for following nodes
            alloc_7: "f32[1, 32]" = executorch_exir_memory_alloc(((1, 32), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:180 in forward, code: x = torch.cat((x[:,:,0],x[:,:,1]), dim=1)
            aten_select_copy_int: "f32[1, 32]" = torch.ops.aten.select_copy.int_out(aten_permute_copy_default, 2, 0, out = alloc_7);  alloc_7 = None
            
            # No stacktrace found for following nodes
            alloc_8: "f32[1, 32]" = executorch_exir_memory_alloc(((1, 32), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:180 in forward, code: x = torch.cat((x[:,:,0],x[:,:,1]), dim=1)
            aten_select_copy_int_1: "f32[1, 32]" = torch.ops.aten.select_copy.int_out(aten_permute_copy_default, 2, 1, out = alloc_8);  aten_permute_copy_default = alloc_8 = None
            
            # No stacktrace found for following nodes
            alloc_9: "f32[1, 64]" = executorch_exir_memory_alloc(((1, 64), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:180 in forward, code: x = torch.cat((x[:,:,0],x[:,:,1]), dim=1)
            aten_cat_default: "f32[1, 64]" = torch.ops.aten.cat.out([aten_select_copy_int, aten_select_copy_int_1], 1, out = alloc_9);  aten_select_copy_int = aten_select_copy_int_1 = alloc_9 = None
            
            # No stacktrace found for following nodes
            alloc_10: "f32[64, 48]" = executorch_exir_memory_alloc(((64, 48), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:183 in forward, code: x = self.linear(x)
            aten_permute_copy_default_1: "f32[64, 48]" = torch.ops.aten.permute_copy.out(p_linear_weight, [1, 0], out = alloc_10);  p_linear_weight = alloc_10 = None
            
            # No stacktrace found for following nodes
            alloc_11: "f32[1, 48]" = executorch_exir_memory_alloc(((1, 48), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:183 in forward, code: x = self.linear(x)
            aten_mm_default: "f32[1, 48]" = torch.ops.aten.mm.out(aten_cat_default, aten_permute_copy_default_1, out = alloc_11);  aten_cat_default = aten_permute_copy_default_1 = alloc_11 = None
            
            # No stacktrace found for following nodes
            alloc_12: "f32[1, 48]" = executorch_exir_memory_alloc(((1, 48), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:184 in forward, code: x = F.relu(x) # ReLu is not linear. At least one non-linear to recognize non-linear pattern
            aten_relu_default_1: "f32[1, 48]" = torch.ops.aten.relu.out(aten_mm_default, out = alloc_12);  aten_mm_default = alloc_12 = None
            
            # No stacktrace found for following nodes
            alloc_13: "f32[48, 2]" = executorch_exir_memory_alloc(((48, 2), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:185 in forward, code: x = F.softmax(self.output(x),dim=1) # Sum = 1
            aten_permute_copy_default_2: "f32[48, 2]" = torch.ops.aten.permute_copy.out(p_output_weight, [1, 0], out = alloc_13);  p_output_weight = alloc_13 = None
            
            # No stacktrace found for following nodes
            alloc_14: "f32[1, 2]" = executorch_exir_memory_alloc(((1, 2), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:185 in forward, code: x = F.softmax(self.output(x),dim=1) # Sum = 1
            aten_mm_default_1: "f32[1, 2]" = torch.ops.aten.mm.out(aten_relu_default_1, aten_permute_copy_default_2, out = alloc_14);  aten_relu_default_1 = aten_permute_copy_default_2 = alloc_14 = None
            
            # No stacktrace found for following nodes
            alloc_15: "f32[1, 2]" = executorch_exir_memory_alloc(((1, 2), torch.float32))
            
             # File: /home/chris/watchplant_classification_dl/pipline_test/train_cnn.py:185 in forward, code: x = F.softmax(self.output(x),dim=1) # Sum = 1
            aten__softmax_default: "f32[1, 2]" = torch.ops.aten._softmax.out(aten_mm_default_1, 1, False, out = alloc_15);  aten_mm_default_1 = alloc_15 = None
            return (aten__softmax_default,)
            
Graph signature: ExportGraphSignature(input_specs=[InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='p_conv1d_1_weight'), target='conv1d_1.weight', persistent=None), InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='p_conv1d_1_bias'), target='conv1d_1.bias', persistent=None), InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='p_linear_weight'), target='linear.weight', persistent=None), InputSpec(kind=<InputKind.PARAMETER: 2>, arg=TensorArgument(name='p_output_weight'), target='output.weight', persistent=None), InputSpec(kind=<InputKind.USER_INPUT: 1>, arg=TensorArgument(name='x'), target=None, persistent=None)], output_specs=[OutputSpec(kind=<OutputKind.USER_OUTPUT: 1>, arg=TensorArgument(name='aten__softmax_default'), target=None)])
Range constraints: {}
```
Calculation:
```
alloc: "f32[1, 32, 96]"

    Elements: 1×32×96=30721×32×96=3072
    Bytes: 3072×4=12 2883072×4=12288 bytes

alloc_1: "f32[1, 32, 96]"

    Same as above: 12,288 bytes

alloc_2: "f32[1, 32, 1, 96]"

    Elements: 1×32×1×96=30721×32×1×96=3072
    Bytes: 3072×4=12 2883072×4=12288 bytes

alloc_3: "f32[1, 32, 1, 32]"

    Elements: 1×32×1×32=10241×32×1×32=1024
    Bytes: 1024×4=4 0961024×4=4096 bytes

alloc_4: "i64[1, 32, 1, 32]"

    Elements: 1×32×1×32=10241×32×1×32=1024
    Bytes (int64): 1024×8=8 1921024×8=8192 bytes

alloc_5: "f32[1, 32, 32]"

    Elements: 1×32×32=10241×32×32=1024
    Bytes: 1024×4=4 0961024×4=4096 bytes

alloc_6: "f32[1, 32, 32]"

    Same as above: 4,096 bytes

alloc_7: "f32[1, 32]"

    Elements: 1×32=321×32=32
    Bytes: 32×4=12832×4=128 bytes

alloc_8: "f32[1, 32]"

    Same as above: 128 bytes

alloc_9: "f32[1, 64]"

    Elements: 1×64=641×64=64
    Bytes: 64×4=25664×4=256 bytes

alloc_10: "f32[64, 48]"

    Elements: 64×48=307264×48=3072
    Bytes: 3072×4=12 2883072×4=12288 bytes

alloc_11: "f32[1, 48]"

    Elements: 1×48=481×48=48
    Bytes: 48×4=19248×4=192 bytes

alloc_12: "f32[1, 48]"

    Same as above: 192 bytes

alloc_13: "f32[48, 2]"

    Elements: 48×2=9648×2=96
    Bytes: 96×4=38496×4=384 bytes

alloc_14: "f32[1, 2]"

    Elements: 1×2=21×2=2
    Bytes: 2×4=82×4=8 bytes

alloc_15: "f32[1, 2]"

    Same as above: 8 bytes

Total: 70,928 bytes.
```

I serialize this graph and then run it on the STM32WB. However the `size_t buffer_size = static_cast<size_t>(method_meta->memory_planned_buffer_size(id).get()) = 33168.`
I don't understand how this size is calculated.

Furthermore, I want to understand how the needed size from the graph above for `m_method_allocator_pool = (uint8_t*)malloc(m_allocator_pool_size)` can be derived.

Thanks in advance,
Christoph
